refactor: update Makefile to use golangci for lint tasks & delete old revive config file
camptocamp/terraboard pull request #163
Opened 2021-06-04 15:24 UTC by hbollon

2021-06-05 05:40 UTC, mcanevet requested changes

2021-06-05 05:40 UTC, mcanevet commented on Makefile
> +	@command -v ~/go/bin/golangci-lint 2>&1 >/dev/null || GO111MODULE=off go get -v github.com/golangci/golangci-lint/cmd/golangci-lint
I wouldn't hardcode the location of the binary here. I guess we can assume that it's available in PATH.

2021-06-05 05:40 UTC, mcanevet commented on Makefile
> +	~/go/bin/golangci-lint run
same here

2021-06-06 10:55 UTC, hbollon commented
I fixed the commitsar issue with one of my commit name and done requested changes :smile:

2021-06-07 11:36 UTC, cryptobioz approved these changes

2021-06-07 12:15 UTC, mcanevet approved these changes

2021-06-07 12:15 UTC, merged